branches:
  except:
  - gh-pages
env:
  global:
  - GH_REPO_NAME: Computing_Project
  - DOXYFILE: "$TRAVIS_BUILD_DIR/Doxyfile"
  - GH_REPO_REF: github.com/mbh1620/Computing_Project.git
  - secure: LJN2/wvji+H1emsFJMYZ5pPAF/gb/EvAgvEglYlyDv4n0fAeFWT5FJscPNddqVf9h8wwMM7BfFYT/EOl88nPwS3VYpKFluQyfnSNbgcpP809oczGzV7/t0mgQUj2ZCKyEOykx4lRF+rc7vBiE8s6NfNnVSVHeFJYrHdHJKtzVnrl9Uwt06mamQYY5rDUF0YAY7si73E3oYTVW6UlSnWMp3EG9jAq3fbuCtqH5sy8TUx4LbLQJY30XT++a2GtkJIFmKS9OIK6pMoyQjBvv5+cV4D6djFTgRTtTb7ewrI+Gff5Q5mJZfWi3BTCipltlfJzzH8Y4m3Nmca1zybWoxr6MByEEwLt5G57owxcBkghs6B7rAgE+bXIWVgc9akGd2y8zPAqA2bguzPxWa4iocScFMnNwMBkpcpIZz0fMBXjtgpZT6xFIhVkKr+ShHrvnoMTI358jPqGIzLOVF3NxlQL5eugQMf5Adj9SUIxYP19cUj854JKqOMvCPiiZtGhOPQRdjA3on3fkf/eUhnRT/58vX84M8wLPSAOpqpPfP4Yy0/CzWxnDAjs1nIdypaKHe3Tfjyo7iMVa63Kt356Ta4SdCIv6oMHT5wvqdGlHOpfmnE9y1N8IYasWsmX9m0fpXrCkZfjC9YDhrbBqsI/wu/yjQRcXo8+x1AnsYnN9+ohZ7o=
addons:
  apt:
    packages:
    - doxygen
    - graphviz
script:
- cmake ./Computing\ project
- make test1
- make test2
- make test3
- make test4
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocumentationAndDeploy.sh 
- ./generateDocumentationAndDeploy.sh